FROM python:3.12-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    libexpat1 \
    libgdal-dev \
    g++ \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir osmium psycopg2-binary

COPY scripts/import-osm-places.py /import-osm-places.py

CMD ["python", "/import-osm-places.py"]