FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libexpat1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    osmium \
    psycopg2-binary

COPY scripts/import-osm-buildings.py /import-osm-buildings.py

ENTRYPOINT ["python", "/import-osm-buildings.py"]
